### PR TITLE
Created Progressive Web App

### LINKED ISSUE #8: PWA
Create the Progressive Web app using `next-pwa` package.

### PR DESCRIPTION
**Pull request by ken1000minus7**
Fixes #8 
### Screenshot
image

### CODE REVIEW

**Review by harshjohar — CHANGES_REQUESTED** [review]
Add a file for a case when internet is not available.
`_offline.tsx`


U my bro so here is the code :kek:, add a few styles if u got some time.

```tsx
import Head from 'next/head';

const Fallback = () => (
	<div className="h-screen w-screen flex justify-centre items-centre overflow-hidden">
		<Head>
			<title>Fabchat |  Connect to internet</title>
		</Head>
		<h1>You are offline</h1>
		<h2>Connect to internet to continue</h2>
	</div>
);

export default Fallback;
```

**Comment by ken1000minus7** [comment]
Oki will do :kek:

**Comment by ken1000minus7** [comment]
@harshjohar 
image

**Review by harshjohar — APPROVED** [review]
sexy! LGTM!

**Pull request merged**
